sudo: required

script:
  - sudo apt -q -yy update
  - sudo apt -q -yy install wget equivs curl
  - bash build.sh

after_success:
  - wget -qO nru https://raw.githubusercontent.com/Nitrux/nitrux-repository-util/master/nitrux-repository-util.sh
  - bash nru *.deb

branches:
  except:
    - "/^(?i:continuous.*)$/"

notifications:
  email: false
