script:
  - bash build.sh

after_success:
  - wget -qO nru https://raw.githubusercontent.com/Nitrux/nitrux-repository-util/master/nitrux-repository-util.sh
  - bash nru out/*

branches:
  except:
    - "/^(?i:continuous.*)$/"

notifications:
  email: false
